load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "json_validation_lib",
    srcs = ["main.go"],
    importpath = "github.com/proxy-wasm/proxy-wasm-go-sdk/examples/json_validation",
    visibility = ["//visibility:private"],
    deps = [
        "//proxywasm",
        "//proxywasm/types",
        "@com_github_tidwall_gjson//:go_default_library",
    ],
)

go_binary(
    name = "json_validation",
    embed = [":json_validation_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "json_validation_test",
    srcs = ["main_test.go"],
    embed = [":json_validation_lib"],
    deps = [
        "//proxywasm/proxytest",
        "//proxywasm/types",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
