load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "receiver_lib",
    srcs = ["main.go"],
    importpath = "github.com/proxy-wasm/proxy-wasm-go-sdk/examples/shared_queue/receiver",
    visibility = ["//visibility:private"],
    deps = [
        "//proxywasm",
        "//proxywasm/types",
    ],
)

go_binary(
    name = "receiver",
    embed = [":receiver_lib"],
    visibility = ["//visibility:public"],
)
