load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "proxytest",
    srcs = [
        "http.go",
        "network.go",
        "option.go",
        "proxytest.go",
        "root.go",
        "wasmwrapper.go",
    ],
    importpath = "github.com/proxy-wasm/proxy-wasm-go-sdk/proxywasm/proxytest",
    visibility = ["//visibility:public"],
    deps = [
        "//proxywasm",
        "//proxywasm/internal",
        "//proxywasm/types",
        "@com_github_tetratelabs_wazero//:wazero",
        "@com_github_tetratelabs_wazero//api",
        "@com_github_tetratelabs_wazero//imports/wasi_snapshot_preview1",
    ],
)

go_test(
    name = "proxytest_test",
    srcs = [
        "http_test.go",
        "timing_off_test.go",
    ],
    embed = [":proxytest"],
    deps = [
        "//proxywasm",
        "//proxywasm/internal",
        "//proxywasm/types",
        "@com_github_stretchr_testify//require",
    ],
)
