load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "properties",
    srcs = [
        "connection.go",
        "pilot.go",
        "properties.go",
        "proxyconfig.go",
        "request.go",
        "response.go",
        "serialization.go",
        "types.go",
        "upstream.go",
        "util.go",
        "wasm.go",
        "xsd.go",
    ],
    importpath = "github.com/proxy-wasm/proxy-wasm-go-sdk/properties",
    visibility = ["//visibility:public"],
    deps = ["//proxywasm"],
)

go_test(
    name = "properties_test",
    srcs = [
        "connection_test.go",
        "pilot_test.go",
        "proxyconfig_test.go",
        "request_test.go",
        "response_test.go",
        "serialization_test.go",
        "types_test.go",
        "upstream_test.go",
        "util_test.go",
        "wasm_test.go",
        "xsd_test.go",
    ],
    embed = [":properties"],
    deps = [
        "//proxywasm/proxytest",
        "@com_github_stretchr_testify//require",
    ],
)
