load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "postpone_requests_lib",
    srcs = ["main.go"],
    importpath = "https:/github.com/walves-cit/proxy-wasm-go-sdk/examples/postpone_requests",
    visibility = ["//visibility:private"],
    deps = [
        "@com_github_proxy_wasm_proxy_wasm_go_sdk//proxywasm:go_default_library",
        "@com_github_proxy_wasm_proxy_wasm_go_sdk//proxywasm/types:go_default_library",
    ],
)

go_binary(
    name = "postpone_requests",
    embed = [":postpone_requests_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "postpone_requests_test",
    srcs = ["main_test.go"],
    embed = [":postpone_requests_lib"],
    deps = [
        "@com_github_proxy_wasm_proxy_wasm_go_sdk//proxywasm/proxytest:go_default_library",
        "@com_github_proxy_wasm_proxy_wasm_go_sdk//proxywasm/types:go_default_library",
        "@com_github_stretchr_testify//require",
    ],
)
