load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "proxywasm",
    srcs = [
        "entrypoint.go",
        "hostcall.go",
    ],
    importpath = "github.com/proxy-wasm/proxy-wasm-go-sdk/proxywasm",
    visibility = ["//visibility:public"],
    deps = [
        "//proxywasm/internal",
        "//proxywasm/types",
    ],
)

go_test(
    name = "proxywasm_test",
    srcs = ["hostcall_test.go"],
    embed = [":proxywasm"],
    deps = [
        "//proxywasm/internal",
        "@com_github_stretchr_testify//require",
    ],
)
