load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "vm_plugin_configuration_lib",
    srcs = ["main.go"],
    importpath = "github.com/proxy-wasm/proxy-wasm-go-sdk/examples/vm_plugin_configuration",
    visibility = ["//visibility:private"],
    deps = [
        "//proxywasm",
        "//proxywasm/types",
    ],
)

go_binary(
    name = "vm_plugin_configuration",
    embed = [":vm_plugin_configuration_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "vm_plugin_configuration_test",
    srcs = ["main_test.go"],
    embed = [":vm_plugin_configuration_lib"],
    deps = [
        "//proxywasm/proxytest",
        "//proxywasm/types",
        "@com_github_stretchr_testify//require",
    ],
)
